on:
  push:
    tags:
      - '*'
    branches:
      - main
env:
  REGISTRY_IMAGE: ghcr.io/duythien/hello_docker
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v7
          - linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,value=latest
            type=ref,event=tag
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push with tags
        id: tags
        if: ${{ github.ref_name != 'main' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ env.REGISTRY_IMAGE }}:latest
      - name: Export digest by tags
        if: ${{ github.ref_name != 'main' }}
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.tags.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}" 

      - name: Build and push with main
        id: main
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ env.REGISTRY_IMAGE }}:latest
      - name: Export digest
        if: ${{ github.ref_name == 'main' }}
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.main.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"  

      - name: Upload digest
        uses: actions/upload-artifact@v3
        with:
          name: digests
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1    
