on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  released-image-docker-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: vban
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push with tags
        if: ${{ github.ref_name != 'main' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: vban/thien:${{  github.ref_name }}

      - name: Build and push with main
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: vban/thien

  released-image-docker-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: vban
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push with tags
        if: ${{ github.ref_name != 'main' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: vban/thien:${{  github.ref_name }}

      - name: Build and push with main
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: vban/thien
